schema_version = "1.0.0"
id = "my_best_pie_menu_ever_debug"
version = "1.0.0"
name = "My Best Pie Menu Ever Debug"
tagline = "Test"
maintainer = "emptybraces <motose6@gmail.com>"
# Supported types: "add-on", "theme"
type = "add-on"

tags = ["3D View", "User Interface"]
blender_version_min = "4.2.0"
license = [
  "SPDX:MIT",
]
